{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: This test is broken", "trace": "def test_broken():\n>       raise Exception(\"This test is broken\")\nE       Exception: This test is broken\n\ntests/pytest_doc/how_to/test_status.py:20: Exception"}, "start": 1751518993187, "stop": 1751518993187, "uuid": "500d12ee-d94e-4e7f-9dc3-03ab48c7980e", "historyId": "7e64cee7709f45cb74575ac5446607e3", "testCaseId": "7e64cee7709f45cb74575ac5446607e3", "fullName": "tests.pytest_doc.how_to.test_status#test_broken", "labels": [{"name": "parentSuite", "value": "tests.pytest_doc.how_to"}, {"name": "suite", "value": "test_status"}, {"name": "host", "value": "pkrvmbietmlfzoi"}, {"name": "thread", "value": "2393-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest_doc.how_to.test_status"}]}